### ISSUE TITLE
Bài 3 em hiểu sai rồi nhé. Thêm nữa là ko viết hàm. Cái này là mỗi lần nó sẽ hiển thị menu và em chọn 1 số cho đến khi nào em bấm số 7

### ISSUE THREAD

**Issue by GuardianOfGods** [duykhanhit/JAVA_HIT#4]
https://github.com/duykhanhit/JAVA_HIT/blob/441b5781a7f75b0fc3dd9aa5cb6dfdbda035d7ab/BTVN_B3/src/Bai3/BT3.java#L1-L76

**Comment by duykhanhit** [comment]
Em nghĩ là phải cho nta nhập các lựa chọn cho đến khi người ta không muốn nhập nữa thì mới thoát chứ ạ

**Comment by GuardianOfGods** [comment]
À ukm đúng rồi a đọc nhầm, Làm ok rồi nhưng lần sau sử dụng hàm cho a nhé
