### ISSUE TITLE
Baì này tư tưởng thuật toán là đúng rồi. Nhưng còn thiếu điều kiện. VD như anh nhập chữ: "ello" nó vẫn in ra YES

### ISSUE THREAD

**Issue by GuardianOfGods** [duykhanhit/JAVA_HIT#5]
https://github.com/duykhanhit/JAVA_HIT/blob/441b5781a7f75b0fc3dd9aa5cb6dfdbda035d7ab/BTVN_B3/src/Bai4/BT4.java#L1-L22

**Comment by duykhanhit** [comment]
Vâng anh, em k biết fix làm sao 😢
